name: ci - cd

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  validate_branch_commit:
    name: Validate Branch and Commit Message
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - name: Validate branch name
        run: bash .husky/scripts/validate-branch-names.sh
        env:
          BRANCH_NAME: ${{ github.head_ref }}

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: [validate_branch_commit]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: npm run lint

  audit_ci:
    name: audit_ci
    runs-on: ubuntu-latest
    needs: [validate_branch_commit]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: npm run audit-ci

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [validate_branch_commit]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: npm run build

  tests:
    name: tests
    runs-on: ubuntu-latest
    needs: [validate_branch_commit]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: npm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  release_draft:
    name: release_drafter
    runs-on: ubuntu-latest
    needs: [lint, audit_ci, build, tests]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v6
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
